/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemlemeRouteImport } from './routes/demleme'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as MagazaRouteImport } from './routes/magaza'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as SosyalRouteImport } from './routes/sosyal'
import { Route as AuthenticatedYonetimRouteImport } from './routes/_authenticated/yonetim'
import { Route as AkademiIndexRouteImport } from './routes/akademi.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DemlemeYontemleriSlugRouteImport } from './routes/demleme-yontemleri.$slug'
import { Route as QrKodRouteImport } from './routes/qr.$kod'
import { Route as UrunSlugRouteImport } from './routes/urun.$slug'
import { Route as AuthenticatedYonetimIndexRouteImport } from './routes/_authenticated/yonetim.index'
import { Route as AuthenticatedYonetimIcerikRouteImport } from './routes/_authenticated/yonetim.icerik'
import { Route as AkademiKategorilerIndexRouteImport } from './routes/akademi.kategoriler.index'
import { Route as AkademiKategorilerSlugRouteImport } from './routes/akademi.kategoriler.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemlemeRoute = DemlemeRouteImport.update({
  id: '/demleme',
  path: '/demleme',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazaRoute = MagazaRouteImport.update({
  id: '/magaza',
  path: '/magaza',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const SosyalRoute = SosyalRouteImport.update({
  id: '/sosyal',
  path: '/sosyal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYonetimRoute = AuthenticatedYonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AkademiIndexRoute = AkademiIndexRouteImport.update({
  id: '/akademi/',
  path: '/akademi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemlemeYontemleriSlugRoute = DemlemeYontemleriSlugRouteImport.update({
  id: '/demleme-yontemleri/$slug',
  path: '/demleme-yontemleri/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QrKodRoute = QrKodRouteImport.update({
  id: '/qr/$kod',
  path: '/qr/$kod',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunSlugRoute = UrunSlugRouteImport.update({
  id: '/urun/$slug',
  path: '/urun/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYonetimIndexRoute =
  AuthenticatedYonetimIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedYonetimRoute,
  } as any)
const AuthenticatedYonetimIcerikRoute =
  AuthenticatedYonetimIcerikRouteImport.update({
    id: '/icerik',
    path: '/icerik',
    getParentRoute: () => AuthenticatedYonetimRoute,
  } as any)
const AkademiKategorilerIndexRoute = AkademiKategorilerIndexRouteImport.update({
  id: '/akademi/kategoriler/',
  path: '/akademi/kategoriler/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkademiKategorilerSlugRoute = AkademiKategorilerSlugRouteImport.update({
  id: '/akademi/kategoriler/$slug',
  path: '/akademi/kategoriler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demleme': typeof DemlemeRoute
  '/iletisim': typeof IletisimRoute
  '/magaza': typeof MagazaRoute
  '/sepet': typeof SepetRoute
  '/sosyal': typeof SosyalRoute
  '/yonetim': typeof AuthenticatedYonetimRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/demleme-yontemleri/$slug': typeof DemlemeYontemleriSlugRoute
  '/qr/$kod': typeof QrKodRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/akademi/': typeof AkademiIndexRoute
  '/yonetim/icerik': typeof AuthenticatedYonetimIcerikRoute
  '/akademi/kategoriler/$slug': typeof AkademiKategorilerSlugRoute
  '/yonetim/': typeof AuthenticatedYonetimIndexRoute
  '/akademi/kategoriler/': typeof AkademiKategorilerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demleme': typeof DemlemeRoute
  '/iletisim': typeof IletisimRoute
  '/magaza': typeof MagazaRoute
  '/sepet': typeof SepetRoute
  '/sosyal': typeof SosyalRoute
  '/api/chat': typeof ApiChatRoute
  '/demleme-yontemleri/$slug': typeof DemlemeYontemleriSlugRoute
  '/qr/$kod': typeof QrKodRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/akademi': typeof AkademiIndexRoute
  '/yonetim/icerik': typeof AuthenticatedYonetimIcerikRoute
  '/akademi/kategoriler/$slug': typeof AkademiKategorilerSlugRoute
  '/yonetim': typeof AuthenticatedYonetimIndexRoute
  '/akademi/kategoriler': typeof AkademiKategorilerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demleme': typeof DemlemeRoute
  '/iletisim': typeof IletisimRoute
  '/magaza': typeof MagazaRoute
  '/sepet': typeof SepetRoute
  '/sosyal': typeof SosyalRoute
  '/_authenticated/yonetim': typeof AuthenticatedYonetimRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/demleme-yontemleri/$slug': typeof DemlemeYontemleriSlugRoute
  '/qr/$kod': typeof QrKodRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/akademi/': typeof AkademiIndexRoute
  '/_authenticated/yonetim/icerik': typeof AuthenticatedYonetimIcerikRoute
  '/akademi/kategoriler/$slug': typeof AkademiKategorilerSlugRoute
  '/_authenticated/yonetim/': typeof AuthenticatedYonetimIndexRoute
  '/akademi/kategoriler/': typeof AkademiKategorilerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demleme'
    | '/iletisim'
    | '/magaza'
    | '/sepet'
    | '/sosyal'
    | '/yonetim'
    | '/api/chat'
    | '/demleme-yontemleri/$slug'
    | '/qr/$kod'
    | '/urun/$slug'
    | '/akademi/'
    | '/yonetim/icerik'
    | '/akademi/kategoriler/$slug'
    | '/yonetim/'
    | '/akademi/kategoriler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demleme'
    | '/iletisim'
    | '/magaza'
    | '/sepet'
    | '/sosyal'
    | '/api/chat'
    | '/demleme-yontemleri/$slug'
    | '/qr/$kod'
    | '/urun/$slug'
    | '/akademi'
    | '/yonetim/icerik'
    | '/akademi/kategoriler/$slug'
    | '/yonetim'
    | '/akademi/kategoriler'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demleme'
    | '/iletisim'
    | '/magaza'
    | '/sepet'
    | '/sosyal'
    | '/_authenticated/yonetim'
    | '/api/chat'
    | '/demleme-yontemleri/$slug'
    | '/qr/$kod'
    | '/urun/$slug'
    | '/akademi/'
    | '/_authenticated/yonetim/icerik'
    | '/akademi/kategoriler/$slug'
    | '/_authenticated/yonetim/'
    | '/akademi/kategoriler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemlemeRoute: typeof DemlemeRoute
  IletisimRoute: typeof IletisimRoute
  MagazaRoute: typeof MagazaRoute
  SepetRoute: typeof SepetRoute
  SosyalRoute: typeof SosyalRoute
  ApiChatRoute: typeof ApiChatRoute
  DemlemeYontemleriSlugRoute: typeof DemlemeYontemleriSlugRoute
  QrKodRoute: typeof QrKodRoute
  UrunSlugRoute: typeof UrunSlugRoute
  AkademiIndexRoute: typeof AkademiIndexRoute
  AkademiKategorilerSlugRoute: typeof AkademiKategorilerSlugRoute
  AkademiKategorilerIndexRoute: typeof AkademiKategorilerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demleme': {
      id: '/demleme'
      path: '/demleme'
      fullPath: '/demleme'
      preLoaderRoute: typeof DemlemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magaza': {
      id: '/magaza'
      path: '/magaza'
      fullPath: '/magaza'
      preLoaderRoute: typeof MagazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sosyal': {
      id: '/sosyal'
      path: '/sosyal'
      fullPath: '/sosyal'
      preLoaderRoute: typeof SosyalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yonetim': {
      id: '/_authenticated/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof AuthenticatedYonetimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/akademi/': {
      id: '/akademi/'
      path: '/akademi'
      fullPath: '/akademi/'
      preLoaderRoute: typeof AkademiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demleme-yontemleri/$slug': {
      id: '/demleme-yontemleri/$slug'
      path: '/demleme-yontemleri/$slug'
      fullPath: '/demleme-yontemleri/$slug'
      preLoaderRoute: typeof DemlemeYontemleriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$kod': {
      id: '/qr/$kod'
      path: '/qr/$kod'
      fullPath: '/qr/$kod'
      preLoaderRoute: typeof QrKodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$slug': {
      id: '/urun/$slug'
      path: '/urun/$slug'
      fullPath: '/urun/$slug'
      preLoaderRoute: typeof UrunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yonetim/': {
      id: '/_authenticated/yonetim/'
      path: '/'
      fullPath: '/yonetim/'
      preLoaderRoute: typeof AuthenticatedYonetimIndexRouteImport
      parentRoute: typeof AuthenticatedYonetimRoute
    }
    '/_authenticated/yonetim/icerik': {
      id: '/_authenticated/yonetim/icerik'
      path: '/icerik'
      fullPath: '/yonetim/icerik'
      preLoaderRoute: typeof AuthenticatedYonetimIcerikRouteImport
      parentRoute: typeof AuthenticatedYonetimRoute
    }
    '/akademi/kategoriler/': {
      id: '/akademi/kategoriler/'
      path: '/akademi/kategoriler'
      fullPath: '/akademi/kategoriler/'
      preLoaderRoute: typeof AkademiKategorilerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akademi/kategoriler/$slug': {
      id: '/akademi/kategoriler/$slug'
      path: '/akademi/kategoriler/$slug'
      fullPath: '/akademi/kategoriler/$slug'
      preLoaderRoute: typeof AkademiKategorilerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedYonetimRouteChildren {
  AuthenticatedYonetimIcerikRoute: typeof AuthenticatedYonetimIcerikRoute
  AuthenticatedYonetimIndexRoute: typeof AuthenticatedYonetimIndexRoute
}

const AuthenticatedYonetimRouteChildren: AuthenticatedYonetimRouteChildren = {
  AuthenticatedYonetimIcerikRoute: AuthenticatedYonetimIcerikRoute,
  AuthenticatedYonetimIndexRoute: AuthenticatedYonetimIndexRoute,
}

const AuthenticatedYonetimRouteWithChildren =
  AuthenticatedYonetimRoute._addFileChildren(AuthenticatedYonetimRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedYonetimRoute: typeof AuthenticatedYonetimRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedYonetimRoute: AuthenticatedYonetimRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemlemeRoute: DemlemeRoute,
  IletisimRoute: IletisimRoute,
  MagazaRoute: MagazaRoute,
  SepetRoute: SepetRoute,
  SosyalRoute: SosyalRoute,
  ApiChatRoute: ApiChatRoute,
  DemlemeYontemleriSlugRoute: DemlemeYontemleriSlugRoute,
  QrKodRoute: QrKodRoute,
  UrunSlugRoute: UrunSlugRoute,
  AkademiIndexRoute: AkademiIndexRoute,
  AkademiKategorilerSlugRoute: AkademiKategorilerSlugRoute,
  AkademiKategorilerIndexRoute: AkademiKategorilerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
